version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bikes_test' 
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    networks:
      backend:
        aliases:
          - db

  api:
    build: .
    depends_on: 
      - mysql
    environment:
      DB_USER: 'test_user'
      DB_PASSWORD: 'test'
      DB_PORT: '3306'
      DB_HOST: 'mysql'
      DB_DATABASE: 'bikes_test'
    command: npm run test:coverage
    ports:
      - '4001'
    volumes:
      - ./coverage:/usr/app/coverage:delegated
    networks:
      - backend

networks:
  backend: